name: roboshop
services:
  mongodb:
    build: ./mongodb
    image: joindevops/mongodb:v1 # docker build -t joindevops/mongodb:v1
    container_name: mongodb # docker run -d --network roboshop joindevops/mongodb:v1
  catalogue:
    build: ./catalogue
    image: joindevops/catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb
  frontend:
    build: ./frontend
    image: joindevops/frontend:v1
    container_name: frontend
    ports:
    - "80:80"


networs:
  default:
   name: roboshop
   driver: bridge
   external: false