name: roboshop
services:
  mongodb:
    build: ./mongodb
    image: roboshop/mongodb
    /mongodb:v1 # docker build -t joindevops/mongodb:v1
    container_name: mongodb # docker run -d --network roboshop joindevops/mongodb:v1
  catalogue:
    build: ./catalogue
    image: roboshop/catalogue
    container_name: catalogue
    depends_on:
    - mongodb
  frontend:
    build: ./frontend
    image: roboshop/frontend
    container_name: frontend
    ports:
    - "80:80"


networks:
  default:
   name: roboshop
   driver: bridge
   external: false